### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [PixelP4radise/house_simulator_rust#1]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install`, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

Thank you.

**Comment by PixelP4radise** [comment]
Thank you for the suggestion and the detailed explanation! This sounds like a great optimization to improve both binary size and performance. I'll work on implementing Fat LTO in the release Profile . I'll work on implementing it with an additional profile for Thin LTO and ensure that it doesn't affect the regular development builds. I'll update the issue once the implementation is ready.

**Comment by PixelP4radise** [comment]
Thank you for the detailed suggestion! I've added Thin LTO to a new `release-thin-lto` profile and added Fat LTO to the default release profile. This way users who want the fastest optimization can just build the default release profile, while users working with less resources can build it with the new Thin profile
